version: '2'

services:

    proxy:
        image: traefik
        ports:
            - "8080:8080"
            - "80:80"
        command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml

    db:
        build:
            context: .
        ports:
            - "8000:8000"

    whoami:
        image: emilevauge/whoami
        labels:
            - "traefik.backend=whoami"
            - "traefik.frontend.rule=Host:whoami.example.org"


